name: Release PR Management

on:
  schedule:
    - cron: '10 11 * * *'
      timezone: 'Asia/Kolkata'

env:
  RELEASE_INIT_BRANCH: release/2026.9.1

jobs:
  release-sync-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          base: 'release/2026.9.2'
          assignees: sairohith2605
          title: 'Release Sync PR'
          branch: ${{ env.RELEASE_INIT_BRANCH }}
